#!/bin/bash
set -x

ArduinoSAMD=~/Library/Arduino15/packages/arduino/hardware/samd/1.6.15
#ArduinoSAMD=testfolder
echo $ArduinoSAMD
cp -Rf etagrfid $ArduinoSAMD/variants/.
cp -f $ArduinoSAMD/boards.txt $ArduinoSAMD/boards.bak
cp -f boards.txt $ArduinoSAMD
